### ISSUE TITLE
Upload server repo

### ISSUE THREAD

**Issue by alvaropinot** [53Lab/contributors-world-map-web#5]
Is there a repo for the server? :) It would be really nice to hack around with the full source code, as `http://contributors-world-map.julces.com:3005/` is not accepting CORS requests 😜

Or `corsproxy` can be used to hack the CORS issue.

Something like the following could do the trick:

**package.json**
```js
  "devDependencies": {
    "corsproxy": "^1.5.0",
  ...
  "scripts": {
    "start": "node env dev && corsproxy & ./node_modules/react-scripts/bin/react-scripts.js start",
```

**env.js**

```js
  const HOSTS = {
    dev: 'http://localhost:1337/contributors-world-map.julces.com:3005/'
```

I can put together a PR with that if you want :)

**Comment by juliomatcom** [comment]
> Is there a repo for the server? :) 

Yes, but it is private for now, I want to use MongoDB instead of LevelDB before make it public, what are your toughs about it :thinking: ?

> ...I can put together a PR with that if you want :)

Awesome! Some concerns is that I though my API was protected by CORS, how naive :disappointed: ... so anybody can burn down my API while developing ?(is limited the amount of call to github API :tractor: )

**Comment by alvaropinot** [comment]
😅 Well you can always rely on GitHub's limit's, or add a rate limiter middleware such as [express-rate-limit](https://www.npmjs.com/package/express-rate-limit)

**Comment by alvaropinot** [comment]
BTW as I see you are using express from the server headers (`X-Powered-BY: Express`), I will encourage you to use [helmet](https://github.com/helmetjs/helmet) to avoid some of the common attacks :) One of the will be to hide the `X-Powered-By` header 😛

**Comment by juliomatcom** [comment]
@alvaropinot  from now on the API is open to all and is protected the maximum amounts of request against github's API.
560962e (do not use credentials)
